BookTutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog'))
]

blog/urls.py
from django.urls import path
from . import  views

app_name='blog'

urlpatterns = [
    path('',views.post_list, name = 'post_list'),
    #path('',views.PostListView.as_view(),name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                        self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250,
                            unique_for_date='publish')
    author=models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,default='draft')

    objects = models.Manager()
    published = PublishedManager()


    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    tags = TaggableManager()

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email=models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name,self.post)





# Create your models here.

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count




class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_share(request,post_id):
    post=get_object_or_404(Post,id=post_id, status='published')
    sent=False

    if request.method=='POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject='{} ({}) zaheca do przeczytania "{}"'.format(cd['name'],
                                                                 cd['email'],post.title)
            message = 'przeczytaj post "{}" na stronie {} \n\n Komentarz dodany' \
                      'przez{}: {}'.format(post.title,post_url,cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent=True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html',  {'post':post,'form':form,'sent':sent})

def post_list(request,tag_slug=None):
    object_list = Post.published.all()
    tag= None
    if tag_slug:
        tag= get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag':tag})

def post_detail(request, year, month ,day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]



    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments':comments,
                   'comment_form':comment_form,
                   'similar_posts':similar_posts})

# Create your views here.

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock  %}</title>
    <link href="{% static "css/blog.css" %}"rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>Moj blog</h2>
        <p>To jest moj blog.</p>
    </div>
</body>
</html>

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{post.title}}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p clas="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}
</p>
{{ post.body|linebreaks }}
    <p>
    <a href="{% url "blog:post_share" post.id %}">
    udostepnij post
    </a>
    <h2> Podobne posty</h2>
    {% for post in similar_posts %}
    <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    nie ma podobnych postow.
    {% endfor %}
    {% with comments.count as total_comments %}
    <h2>
    {{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
    </h2>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
    <p class="info">
        Komentarz {{  forloop.counter }} dodany przez {{ comment.name }} {{ comment.created }}
    </p>
    {{comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>nie ma jeszcze zadnych komentarzy</p>
    {% endfor %}
    {% if new_comment %}
    <h2>Twoj komentarz zostal dodany</h2>
    {% else %}
    <h2>dodaj nowy komentarz</h2>
    <form action="."method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit"value="Dodaj komentarz"></p>

    </form>
    {% endif %}

{% endblock %}

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Moj blog{% endblock %}
{% block content %}
<h1>Moj blog</h1>
    {% if tag %}
    <h2>Posty oznaczone tagiem "{{ tag.name }}</h2>
    {% endif %}

{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
        <p class="tags">Tagi: {{ post.tags.all|join:", " }}</p>
        {% for tag in post.tags.all %}
            <a href="{%  url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
            </a>
    </a>

</h2>
<p clas="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}

</p>
{{ post.body|truncatewords:30|linebreaks }}

{% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %} Udostepnij post{% endblock %}
{% block content %}
{% if sent %}
<h1>wiadomosc email zostala wyslana</h1>
    <p>
    wyslanie posta "{{ post.title }}" do {{ cd.to }} zakonoczna sukcesem
    </p>
    {% else %}
    <h1>
        udostepnij "{{ post.title }}" przez email</h1>
    <form action="."method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="wyslij wiadomosc email">
    </form>

{% endif %}
{% endblock %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}

        <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Nastepna</a>
        {% endif %}
    </span>
</div>